services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    restart: always
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5431:5432"

  main-db:
    image: postgres:16.1
    container_name: main-db
    restart: always
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"

