server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        # comment-service
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /user/*/comments/**, /comments/**

        # request-service
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests/**

        # user-service
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        # main-service
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**, /users/**, /user/**, /events/**, /categories/**, /compilations/**, /comments/**


