server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

logging:
  level:
    root: INFO

spring:
  sql:
    init:
      # Всегда выполнять скрипты при старте
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/stats-db
    username: user
    password: user