stats-server-url: http://localhost:9090

server:
  port: 8080
logging:
  level:
    root: INFO

spring:
  sql:
    init:
      # Всегда выполнять скрипты при старте
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main-db
    username: user
    password: user
